#!/bin/bash
curl -X DELETE "http://localhost:3000/api/results/226" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/149" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/147" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/144" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/134" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/128" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/126" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/118" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/116" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/115" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/114" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/108" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/105" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/101" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/98" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/95" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/86" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/84" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/80" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/75" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/73" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/65" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/57" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/52" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/29" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/32" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/35" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/47" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/56" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/7" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/8" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/9" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/69" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/70" >/dev/null
curl -X DELETE "http://localhost:3000/api/results/10" >/dev/null
